name: CI/CD Pipeline
on:
  push:
    branches: [main,master]
  pull_request:
    branches: [main,master]

jobs:
  test-push:
    runs-on: ubuntu-latest

    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 安装python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 安装环境依赖
        run: pip install -r requirements.txt

      - name: 运行
        run: pytest -v -s

      - name: 登录阿里云
        run: |
          echo "${{secrets.ALIYUN_PASSWORD}}" | docker login --username=${{secrets.ALIYUN_USERNAME}} crpi-u2e370cqx4idzcz9.cn-guangzhou.personal.cr.aliyuncs.com --password-stdin

      - name: 构建镜像
        run: docker build -t crpi-u2e370cqx4idzcz9.cn-guangzhou.personal.cr.aliyuncs.com/lxself-test/my-note-test:latest .

      - name: 推送镜像
        run: docker push crpi-u2e370cqx4idzcz9.cn-guangzhou.personal.cr.aliyuncs.com/lxself-test/my-note-test:latest
